name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up Golang
      uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    # TODO remove after https://github.com/actions/setup-go/issues/14
    - name: Add GOPATH/bin to PATH
      shell: bash
      run: |
        echo "##[set-env name=GOPATH;]$(go env GOPATH)"
        echo "##[add-path]$(go env GOPATH)/bin"
    - name: Install ko
      run: go get github.com/google/ko/cmd/ko
    - name: Run tests
      run: make build test
    - name: Build using ko
      run: ko publish -L github.com/projectriff/nop-provisioner/cmd/provisioner
    - name: Publish
      if: |
        success() && 
        github.event_name == 'push' && (
          github.ref == 'refs/heads/master' || (
            startsWith(github.ref, 'refs/heads/v') && endsWith(github.ref, 'x')
          )
        )
      run: ${GITHUB_WORKSPACE}/.github/workflows/publish.sh
      env:
        GCLOUD_CLIENT_SECRET: ${{ secrets.GCLOUD_CLIENT_SECRET }}
